[package]
name = "agents"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

[[bin]]
name = "core"
path = "core/src/server.rs"

[[bin]]
name = "jsongrpc"
path = "jsongrpc/src/server.rs"

[lib]
name = "common"
path = "common/src/lib.rs"

[dependencies]
structopt = "0.3.15"
tokio = { version = "0.2", features = ["full"] }
tonic = "0.1"
futures = "0.3.8"
serde_json = "1.0"
async-trait = "=0.1.42"
dyn-clonable = "0.9.0"
smol = "1.0.0"
snafu = "0.6"
lazy_static = "1.4.0"
humantime = "2.0.1"
state = "0.4.2"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
http = "0.2.3"
paste = "1.0.4"
common-lib = { path = "../../common" }
reqwest = "0.10.0"

[dev-dependencies]
composer = { path = "../../composer" }
ctrlp-tests = { path = "../../tests-mayastor" }
actix-rt = "1.1.1"
actix-web = { version = "3.2.0", features = ["rustls"] }
url = "2.2.0"
once_cell = "1.4.1"

[dependencies.serde]
features = ["derive"]
version = "1.0"
